// scripts/lib/stack-audit.mjs — auditor for .context/stacks/refs/<lib>@<version>.md.
//
// Implements pragmatic subset of roadmap-futuro-validacao-pipeline.md Item 2
// (5 of 12 checks — high-value/easy-to-implement). Remaining 7 deferred to
// v1.2+ (require HEAD requests, AST parsing, anti-API dictionary).
//
// Implemented checks:
//   T1 (cat 1.1)  Manifest entry exists for this <lib>@<version>
//   T2 (cat 3.1)  All snippets have full TITLE/DESCRIPTION/SOURCE/LANGUAGE/CODE headers
//   T3 (cat 3.3)  File size within expected band (≥1KB, ≥1 snippet, warn if <5)
//   T4 (cat 1.5)  SI-6 fence canary intact (start/end markers + sha256 hash)
//   T5 (cat 1.4)  Provenance log: file presence + non-zero (no scaffold/manual generation marker)
//
// Roadmap items deferred:
//   1.1 SOURCE HEAD requests (network), 1.2 version match deep, 1.3 drift markers,
//   2.1 snippets compile (tsc spawn), 2.2 anti-API dictionary, 2.3 topics coverage,
//   2.4 manual sample audit log

import { readFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { loadManifest } from "./manifest-stacks.mjs";

const FENCE_START_RE = /<<<DEVFLOW_STACK_REF_START_([0-9a-f]+)>>>/;
const FENCE_END_RE = /<<<DEVFLOW_STACK_REF_END>>>/;
const REQUIRED_HEADERS = ["TITLE:", "DESCRIPTION:", "SOURCE:", "LANGUAGE:", "CODE:"];

// Minimum reasonable size by lib type (very permissive — real lib docs are 10s of KB)
const MIN_SIZE_BYTES = 500;
const WARN_BELOW_SNIPPETS = 5;

// Markers that strongly suggest the ref was hand-written or LLM-generated
// instead of produced by the scrape pipeline. False-positive sensitive — we
// want patterns that almost never appear in real upstream docs.
//
// Past false positives (anchored to comments/disclaimers, not prose):
//   - "manually created" appeared in Python whatsnew prose about PEP 695
//     ("Manually created type variables may be explicitly marked..."). The
//     loose /manually created/i caught it. Fix: require comment delimiter
//     or standalone disclaimer line.
const MANUAL_GENERATION_MARKERS = [
  // HTML comment disclaimers
  /<!--\s*(manually created|hand-?written|generated by (LLM|AI|Claude|GPT|Gemini))\s*-->/i,
  // Heading-line disclaimers (1st-2nd line of a section)
  /^#{1,6}\s+(manually created|hand-?written|TODO[: ].*scrape)/im,
  // Bracketed AI/LLM banners
  /\[\s*(LLM|AI|Claude|GPT|Gemini)[- ]generated\s*\]/i,
  // Explicit pipeline-skip disclaimers (single-line)
  /^(NOTE|WARNING|DISCLAIMER):\s*(this (file|ref|content) (is|was) (manually|hand)).*/im,
];

export function auditStack(lib, version, projectRoot) {
  const refRelative = `refs/${lib}@${version}.md`;
  const refPath = join(projectRoot, ".context", "stacks", refRelative);
  const checks = [];

  // T1 — Manifest entry exists for this lib@version
  {
    const manifest = loadManifest(projectRoot);
    const fw = manifest.frameworks?.[lib];
    if (!fw) {
      checks.push({
        id: "T1",
        name: "Manifest entry",
        status: "FAIL",
        diagnosis: `'${lib}' not declared in manifest.yaml`,
      });
    } else if (fw.skipDocs) {
      checks.push({
        id: "T1",
        name: "Manifest entry",
        status: "PASS",
        diagnosis: `'${lib}' has skipDocs:true (audit short-circuits)`,
      });
      // Skip remaining checks
      const summary = { pass: 1, fail: 0, warn: 0 };
      return { lib, version, file: refPath, checks, summary, gate: "PASSED" };
    } else if (fw.version !== version) {
      checks.push({
        id: "T1",
        name: "Manifest entry",
        status: "WARN",
        diagnosis: `'${lib}' manifest version=${fw.version}, audit target=${version} (drift)`,
      });
    } else if (fw.mcpIndexed === true) {
      // Fase B: lib indexed in docs-mcp-server global store. Audit
      // short-circuits — content checks T2-T5 don't apply (no .md to read).
      // Full verification of MCP-indexed libs requires querying the MCP
      // server, which is out of scope for the static audit.
      checks.push({
        id: "T1",
        name: "Manifest entry",
        status: "PASS",
        diagnosis: `${lib}@${version} declared with mcpIndexed:true (query via mcp__docs-mcp-server__search_docs to verify content)`,
      });
      const summary = { pass: 1, fail: 0, warn: 0 };
      return { lib, version, file: null, checks, summary, gate: "PASSED" };
    } else {
      checks.push({
        id: "T1",
        name: "Manifest entry",
        status: "PASS",
        diagnosis: `${lib}@${version} declared with artisanalRef=${fw.artisanalRef}`,
      });
    }
  }

  // Bail if file missing — remaining checks need content
  if (!existsSync(refPath)) {
    checks.push({
      id: "T_FILE",
      name: "Ref file exists",
      status: "FAIL",
      diagnosis: `not found: ${refPath} (run 'devflow stacks scrape ${lib} ${version}')`,
    });
    return {
      lib, version, file: refPath, checks,
      summary: { pass: checks.filter(c => c.status === "PASS").length, fail: 1, warn: 0 },
      gate: "BLOCKED",
    };
  }

  const content = readFileSync(refPath, "utf-8");
  const stats = statSync(refPath);

  // Format detector: refs come in 2 shapes during the transition.
  //   Legacy (md2llm fetch-url):  multiple "TITLE:/DESCRIPTION:/SOURCE:/LANGUAGE:/CODE:" headers
  //   Current (recursive scrape): "**URL:** <url>" markers, 1 per crawled page
  const titles = (content.match(/^TITLE:/gm) || []).length;
  const urlMarkers = (content.match(/^\*\*URL:\*\*\s+https?:\/\//gm) || []).length;
  const isLegacy = titles > 0;
  const isRecursive = urlMarkers > 0;
  const unitCount = Math.max(titles, urlMarkers);

  // T2 — Structural headers consistent for the detected format
  {
    if (!isLegacy && !isRecursive) {
      checks.push({
        id: "T2",
        name: "Structural markers",
        status: "FAIL",
        diagnosis: "zero structural markers (no TITLE: nor **URL:** headers — likely empty scrape)",
      });
    } else if (isRecursive) {
      // New format — pages with **URL:** markers
      checks.push({
        id: "T2",
        name: "Structural markers",
        status: "PASS",
        diagnosis: `${urlMarkers} page(s) crawled (recursive scrape format)`,
      });
    } else {
      // Legacy md2llm format — verify all 5 header types are present and consistent
      const missing = REQUIRED_HEADERS.filter(h => !content.includes(h));
      if (missing.length > 0) {
        checks.push({
          id: "T2",
          name: "Structural markers",
          status: "WARN",
          diagnosis: `${titles} snippet(s) but missing global header types: ${missing.join(", ")}`,
        });
      } else {
        const counts = REQUIRED_HEADERS.map(h => ({
          h,
          count: (content.match(new RegExp(`^${h.replace(":", "")}:`, "gm")) || []).length,
        }));
        const inconsistent = counts.filter(c => c.count !== titles);
        if (inconsistent.length > 0) {
          checks.push({
            id: "T2",
            name: "Structural markers",
            status: "WARN",
            diagnosis: `header counts inconsistent: ${counts.map(c => `${c.h}=${c.count}`).join(", ")} (titles=${titles})`,
          });
        } else {
          checks.push({
            id: "T2",
            name: "Structural markers",
            status: "PASS",
            diagnosis: `${titles} snippet(s) (legacy md2llm format), all 5 header types consistent`,
          });
        }
      }
    }
  }

  // T3 — File size + unit count within band
  {
    const unitLabel = isRecursive ? "page(s)" : "snippet(s)";
    if (stats.size < MIN_SIZE_BYTES) {
      checks.push({
        id: "T3",
        name: "Size band",
        status: "FAIL",
        diagnosis: `${stats.size} bytes (< ${MIN_SIZE_BYTES} minimum) — likely scrape failure`,
      });
    } else if (unitCount < WARN_BELOW_SNIPPETS) {
      checks.push({
        id: "T3",
        name: "Size band",
        status: "WARN",
        diagnosis: `only ${unitCount} ${unitLabel} (expected ≥${WARN_BELOW_SNIPPETS} for non-trivial libs)`,
      });
    } else {
      checks.push({
        id: "T3",
        name: "Size band",
        status: "PASS",
        diagnosis: `${stats.size} bytes, ${unitCount} ${unitLabel}`,
      });
    }
  }

  // T4 — SI-6 fence canary intact + hash matches content
  {
    const startMatch = content.match(FENCE_START_RE);
    const endMatch = content.match(FENCE_END_RE);
    if (!startMatch) {
      checks.push({
        id: "T4",
        name: "SI-6 fence canary",
        status: "FAIL",
        diagnosis: "missing <<<DEVFLOW_STACK_REF_START_<hash>>>> opening fence",
      });
    } else if (!endMatch) {
      checks.push({
        id: "T4",
        name: "SI-6 fence canary",
        status: "FAIL",
        diagnosis: "missing <<<DEVFLOW_STACK_REF_END>>> closing fence (file truncated?)",
      });
    } else {
      const declaredHash = startMatch[1];
      // Extract content between fences and recompute hash to compare
      const inner = content
        .replace(FENCE_START_RE, "")
        .replace(/^[\r\n]+/, "")
        .replace(FENCE_END_RE, "")
        .replace(/\n$/, "");
      // sanitize-snippet uses sha256 of the consolidated content BEFORE fence wrap.
      // We can't perfectly reverse, but we can verify the declared hash format.
      if (!/^[0-9a-f]{8,64}$/.test(declaredHash)) {
        checks.push({
          id: "T4",
          name: "SI-6 fence canary",
          status: "WARN",
          diagnosis: `fence hash '${declaredHash}' has unexpected format`,
        });
      } else {
        checks.push({
          id: "T4",
          name: "SI-6 fence canary",
          status: "PASS",
          diagnosis: `fence intact (canary=${declaredHash.slice(0, 12)}...)`,
        });
      }
    }
  }

  // T5 — No manual-generation markers (per roadmap Item 1)
  {
    const flagged = MANUAL_GENERATION_MARKERS.find(re => re.test(content));
    if (flagged) {
      checks.push({
        id: "T5",
        name: "No manual-generation markers",
        status: "FAIL",
        diagnosis: `content contains manual-generation marker (pattern: ${flagged.source.slice(0, 40)}...) — re-run pipeline`,
      });
    } else {
      checks.push({
        id: "T5",
        name: "No manual-generation markers",
        status: "PASS",
        diagnosis: "no manual-generation markers detected",
      });
    }
  }

  const summary = {
    pass: checks.filter(c => c.status === "PASS").length,
    fail: checks.filter(c => c.status === "FAIL").length,
    warn: checks.filter(c => c.status === "WARN").length,
  };
  const gate = summary.fail === 0 ? "PASSED" : "BLOCKED";

  return { lib, version, file: refPath, checks, summary, gate };
}
